"""Builds PhotoCuller.app, the bundle ON1 sends photographs to.

    python3 on1_plugin/install.py

ON1 cannot run a script. It can hand a selection to another application, so the plugin
has to be one. The bundle is a five-line AppleScript droplet -- the only kind of
application macOS lets you build with nothing but the tools already on the machine --
whose entire job is to catch the "open these documents" event and pass the paths to
app.py. Everything the photographer sees comes from Python.

The droplet holds no logic and no copy of the project: it runs the code where it sits,
so a git pull changes the plugin's behaviour with no rebuild. Rebuild only if the
project moves or you point it at a different Python.
"""

from pathlib import Path
from typing import List, Optional
import argparse
import plistlib
import shutil
import subprocess
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BUNDLE_NAME = "PhotoCuller.app"
BUNDLE_ID = "io.github.filipfilm.photoculler"

# tkinter is the awkward one: Homebrew ships it separately, so the interpreter that can
# run the culler is often not one that can draw a window. Both are required here.
REQUIRED_MODULES = ["tkinter", "PIL", "PIL.ImageTk", "click", "ollama", "rawpy", "cv2"]

CANDIDATE_INTERPRETERS = [
    sys.executable,
    "/opt/homebrew/bin/python3.11",
    "/opt/homebrew/bin/python3.12",
    "/opt/homebrew/bin/python3.13",
    "/opt/homebrew/bin/python3",
    "/usr/local/bin/python3",
]

DROPLET_SOURCE = """
on run
\tlaunchWith({})
end run

on open theItems
\tset paths to {}
\trepeat with anItem in theItems
\t\tset end of paths to POSIX path of anItem
\tend repeat
\tlaunchWith(paths)
end open

on launchWith(paths)
\tset launcher to POSIX path of (path to resource "launch.sh")
\tset cmd to quoted form of launcher
\trepeat with p in paths
\t\tset cmd to cmd & " " & quoted form of (p as text)
\tend repeat
\t-- Detached, so the droplet can quit and leave the review window running. Without
\t-- the background ampersand ON1 waits on us and AppleScript times out after 2 min.
\tdo shell script cmd & " > /dev/null 2>&1 &"
end launchWith
"""

LAUNCHER_SOURCE = """#!/bin/sh
# Generated by on1_plugin/install.py -- edit that, not this.
LOG="$HOME/Library/Logs/PhotoCuller.log"
LIVE={live}
SNAPSHOT={snapshot}

# macOS refuses an unsigned application access to ~/Documents, ~/Desktop and
# ~/Downloads until it is granted Full Disk Access, and refuses it silently -- the
# plugin would simply never open a window. So the installer leaves a copy of the
# project somewhere always readable, and the live checkout wins whenever it can
# actually be opened. Grant PhotoCuller.app Full Disk Access and this flips back to
# running your working tree with no reinstall.
if head -c 1 "$LIVE" >/dev/null 2>&1; then
\tENTRY="$LIVE"
else
\tENTRY="$SNAPSHOT"
fi

exec {python} "$ENTRY" "$@" >>"$LOG" 2>&1
"""

# Where macOS gates access behind Full Disk Access. ~/Pictures is protected too, but
# photographs are passed to us as arguments by an application the photographer chose,
# which is the case TCC is built to allow.
TCC_PROTECTED_DIRS = [
    Path.home() / "Documents",
    Path.home() / "Desktop",
    Path.home() / "Downloads",
    Path.home() / "Library" / "Mobile Documents",
]

SNAPSHOT_DIR = Path.home() / "Library" / "Application Support" / "PhotoCuller" / "project"

# The snapshot only has to run the analysis, so the git history, caches and run
# artefacts stay behind.
SNAPSHOT_IGNORE = shutil.ignore_patterns(
    ".git", "__pycache__", "*.pyc", "cull_runs", ".photo_culler_config", "*.csv",
    ".venv", "venv", ".DS_Store",
)


def check_interpreter(python: str) -> List[str]:
    """The modules this interpreter is missing. Empty means it can run the plugin."""
    if not Path(python).exists():
        return REQUIRED_MODULES
    probe = (
        "import importlib, sys\n"
        f"missing = [m for m in {REQUIRED_MODULES!r} "
        "if importlib.util.find_spec(m) is None]\n"
        "print(','.join(missing))"
    )
    try:
        out = subprocess.run(
            [python, "-c", probe], capture_output=True, text=True, timeout=60
        )
    except Exception:
        return REQUIRED_MODULES
    if out.returncode != 0:
        return REQUIRED_MODULES
    return [m for m in out.stdout.strip().split(",") if m]


def find_interpreter(explicit: Optional[str]) -> str:
    if explicit:
        missing = check_interpreter(explicit)
        if missing:
            raise SystemExit(
                f"{explicit} cannot run the plugin; missing: {', '.join(missing)}"
            )
        return explicit

    tried = []
    for candidate in CANDIDATE_INTERPRETERS:
        missing = check_interpreter(candidate)
        if not missing:
            return candidate
        tried.append(f"  {candidate}: missing {', '.join(missing)}")

    hint = ""
    if any("tkinter" in line for line in tried):
        hint = (
            "\n\ntkinter is packaged separately by Homebrew. For python 3.11:\n"
            "  brew install python-tk@3.11"
        )
    raise SystemExit(
        "No interpreter on this machine can run both the culler and its window.\n"
        + "\n".join(tried) + hint
    )


def needs_snapshot() -> bool:
    return any(
        PROJECT_ROOT == parent or parent in PROJECT_ROOT.parents
        for parent in TCC_PROTECTED_DIRS
    )


def write_snapshot() -> Path:
    """Copy the project somewhere the bundle is allowed to read."""
    if SNAPSHOT_DIR.exists():
        shutil.rmtree(SNAPSHOT_DIR)
    SNAPSHOT_DIR.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(PROJECT_ROOT, SNAPSHOT_DIR, ignore=SNAPSHOT_IGNORE, symlinks=True)
    return SNAPSHOT_DIR


def write_launcher(bundle: Path, python: str, snapshot: Optional[Path]):
    live_entry = PROJECT_ROOT / "on1_plugin" / "app.py"
    snapshot_entry = (snapshot / "on1_plugin" / "app.py") if snapshot else live_entry

    launcher = bundle / "Contents" / "Resources" / "launch.sh"
    launcher.write_text(
        LAUNCHER_SOURCE.format(
            python=shell_quote(python),
            live=shell_quote(str(live_entry)),
            snapshot=shell_quote(str(snapshot_entry)),
        )
    )
    launcher.chmod(0o755)


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def patch_info_plist(bundle: Path):
    """Teach macOS that this application opens photographs.

    Without CFBundleDocumentTypes the droplet still receives files dropped on its icon,
    but it does not appear in Finder's Open With menu and ON1's picker greys it out.
    """
    plist_path = bundle / "Contents" / "Info.plist"
    with open(plist_path, "rb") as handle:
        info = plistlib.load(handle)

    info["CFBundleName"] = "PhotoCuller"
    info["CFBundleDisplayName"] = "PhotoCuller"
    info["CFBundleIdentifier"] = BUNDLE_ID
    info["CFBundleShortVersionString"] = "1.0"
    info["CFBundleDocumentTypes"] = [
        {
            "CFBundleTypeName": "Photograph",
            "CFBundleTypeRole": "Editor",
            "LSHandlerRank": "Alternate",
            "LSItemContentTypes": [
                "public.image",
                "public.camera-raw-image",
                "public.tiff",
                "public.jpeg",
                "public.png",
                "public.heic",
                "com.adobe.photoshop-image",
            ],
        },
        {
            # ON1 hands over whatever the Send To dialog rendered, and a UTI-based match
            # can miss for camera-specific RAW types macOS does not know. Extensions
            # catch what the type list misses.
            "CFBundleTypeName": "Photograph (by extension)",
            "CFBundleTypeRole": "Editor",
            "LSHandlerRank": "Alternate",
            "CFBundleTypeExtensions": [
                "nef", "cr2", "cr3", "arw", "dng", "raf", "orf", "rw2", "pef", "srw",
                "jpg", "jpeg", "heic", "heif", "tif", "tiff", "psd", "psb", "png",
            ],
        },
    ]

    with open(plist_path, "wb") as handle:
        plistlib.dump(info, handle)


def register_with_launch_services(bundle: Path):
    """Make the new bundle show up in Open With without a logout."""
    lsregister = (
        "/System/Library/Frameworks/CoreServices.framework/Frameworks/"
        "LaunchServices.framework/Support/lsregister"
    )
    if Path(lsregister).exists():
        subprocess.run([lsregister, "-f", str(bundle)], capture_output=True, timeout=60)


def build(destination: Path, python: str, force: bool) -> tuple:
    bundle = destination / BUNDLE_NAME

    if bundle.exists():
        if not force:
            raise SystemExit(f"{bundle} already exists. Re-run with --force to replace it.")
        shutil.rmtree(bundle)

    destination.mkdir(parents=True, exist_ok=True)

    source = destination / "PhotoCuller.applescript"
    source.write_text(DROPLET_SOURCE)
    try:
        result = subprocess.run(
            ["/usr/bin/osacompile", "-o", str(bundle), str(source)],
            capture_output=True, text=True, timeout=120,
        )
        if result.returncode != 0:
            raise SystemExit(f"osacompile failed:\n{result.stderr}")
    finally:
        source.unlink(missing_ok=True)

    snapshot = write_snapshot() if needs_snapshot() else None
    write_launcher(bundle, python, snapshot)
    patch_info_plist(bundle)
    register_with_launch_services(bundle)
    return bundle, snapshot


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dest", default=str(Path.home() / "Applications"),
        help="Where to build the bundle. Default: ~/Applications",
    )
    parser.add_argument(
        "--python", default=None,
        help="Interpreter to run the culler with. Default: the first one that can.",
    )
    parser.add_argument("--force", action="store_true", help="Replace an existing bundle.")
    args = parser.parse_args()

    python = find_interpreter(args.python)
    bundle, snapshot = build(Path(args.dest).expanduser(), python, args.force)

    print(f"Built    {bundle}")
    print(f"Python   {python}")
    print(f"Runs     {PROJECT_ROOT / 'on1_plugin' / 'app.py'}")
    print(f"Log      {Path.home() / 'Library' / 'Logs' / 'PhotoCuller.log'}")
    if snapshot:
        print()
        print("This project lives somewhere macOS keeps unsigned applications out of, so")
        print("a copy it can read was left in:")
        print(f"  {snapshot}")
        print("Re-run this installer after changing the code -- or give PhotoCuller.app")
        print("Full Disk Access in System Settings > Privacy & Security, after which it")
        print("runs your working tree directly and the copy stops being used.")
    print()
    print("In ON1 Photo RAW: select photos in Browse, right-click, Send to,")
    print(f"Send to Other Application..., and choose {bundle}.")
    print("ON1 remembers it, so after the first time it is just Send to > PhotoCuller.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
